title: may's website
description: uuggghhhhhhhh
author: ezist
markdown: kramdown
plugins:
  - jekyll-github-metadata
  - jekyll-loading-lazy
  - jekyll-extlinks
  - jekyll-feed
repository: ezist/ezist.github.io
keep_files:
  - .git
  - avatar.png
  - key.asc
  - keybase.txt
  - style.css
extlinks:
  attributes: {rel: nofollow, target: _blank}