title: five's website
description: uuggghhhhhhhh
author: ezist
markdown: kramdown
plugins:
  - jekyll-github-metadata
  - jekyll-loading-lazy
  - jekyll-extlinks
  - jekyll-feed
permalink: pretty
repository: ezist/ezist.github.io
keep_files:
  - .git
  - avatar.png
  - key.asc
  - keybase.txt
feed:
  excerpt_only: true
extlinks:
  attributes: {rel: nofollow, target: _blank}
